NIAD-1182: Global Logging
nhsconnect/integration-adaptor-gpc-consumer pull request #26
Opened 2021-03-26 12:24 UTC by ElliotB-96

- Added MDC handling
- updated logback to better meet specified format

2021-03-26 16:36 UTC, z-uddin approved these changes
From looking at the pipeline logs for the tests can observe Ssp-TraceId is logged when Ssp-TraceId is present. And RequestId being logged when a request is made to the GPCC adaptor in the test logs.

2021-03-26 16:57 UTC, mattd-kainos requested changes
Doesn't meet AC 1 - nothing is logged for requests that are not routed

2021-03-29 11:20 UTC, andrewwa-kainos reviewed
Some observations - all minor; nothing that I'd insist on

2021-03-29 11:20 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gpc/consumer/filters/ReactorMdcSupport.java
> +            },
Possible alternative
```suggestion
            publisher -> MDC.getCopyOfContextMap() != null
                && !(publisher instanceof Fuseable.ScalarCallable),
```

2021-03-29 11:20 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gpc/consumer/filters/ReactorMdcSupport.java
> +            ((publisher, coreSubscriber) -> new MdcPropagatingSubscriber<>(coreSubscriber))
Minor point: the wrapping parentheses are superfluous, but harmless
```suggestion
            (publisher, coreSubscriber) -> new MdcPropagatingSubscriber<>(coreSubscriber)
```

2021-03-29 11:20 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gpc/consumer/filters/ReactorMdcSupport.java
> +            }
If you're comfortable with the ternary conditional operator
```suggestion
            Context context = currentContext.hasKey(MDC_CONTEXT_KEY)
                ? currentContext
                : currentContext.put(MDC_CONTEXT_KEY, new HashMap<>(MDC.getCopyOfContextMap()));
```

2021-03-29 11:20 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gpc/consumer/filters/ReactorMdcSupport.java
> +public class ReactorMdcSupport {
This class seems to be a decorator - so could we call it `ReactorMdcSupportDecorator` to make that clear?

2021-03-29 11:20 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gpc/consumer/utils/MdcUtil.java
> +        var traceId = headers.get(TRACE_ID);
For anyone unfamiliar with spring it won't be immediately clear what type `traceId` is so in this case I'd advise against `var`.
```suggestion
        List<String> traceId = headers.get(TRACE_ID);
```

2021-03-29 11:20 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gpc/consumer/utils/MdcUtil.java
> +        if (traceId != null && traceId.size() > 0) {
Lists have a method for this
```suggestion
        if (traceId != null && !traceId.isEmpty()) {
```

2021-03-30 08:09 UTC, mattd-kainos approved these changes
looks great, logging works for both routed and non-routed paths including identifiers

2021-03-30 08:37 UTC, z-uddin approved these changes

2021-03-30 08:39 UTC, merged